// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"local/custom-server/client/operations"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationOperationsGetGreetingCmd returns a cmd to handle operation getGreeting
func makeOperationOperationsGetGreetingCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getGreeting",
		Short: ``,
		RunE:  runOperationOperationsGetGreeting,
	}

	if err := registerOperationOperationsGetGreetingParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationOperationsGetGreeting uses cmd flags to call endpoint api
func runOperationOperationsGetGreeting(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := operations.NewGetGreetingParams()
	if err, _ := retrieveOperationOperationsGetGreetingNameFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationOperationsGetGreetingResult(appCli.Operations.GetGreeting(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationOperationsGetGreetingParamFlags registers all flags needed to fill params
func registerOperationOperationsGetGreetingParamFlags(cmd *cobra.Command) error {
	if err := registerOperationOperationsGetGreetingNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationOperationsGetGreetingNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	nameDescription := `defaults to World if not given`

	var nameFlagName string
	if cmdPrefix == "" {
		nameFlagName = "name"
	} else {
		nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var nameFlagDefault string

	_ = cmd.PersistentFlags().String(nameFlagName, nameFlagDefault, nameDescription)

	return nil
}

func retrieveOperationOperationsGetGreetingNameFlag(m *operations.GetGreetingParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var nameFlagName string
		if cmdPrefix == "" {
			nameFlagName = "name"
		} else {
			nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		nameFlagValue, err := cmd.Flags().GetString(nameFlagName)
		if err != nil {
			return err, false
		}
		m.Name = &nameFlagValue

	}
	return nil, retAdded
}

// parseOperationOperationsGetGreetingResult parses request result and return the string content
func parseOperationOperationsGetGreetingResult(resp0 *operations.GetGreetingOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*operations.GetGreetingOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr := fmt.Sprintf("%v", resp0.Payload)
		return string(msgStr), nil
	}

	return "", nil
}
